### ISSUE TITLE
linuxmuster-webui7 1.0.41-1: config.yml does not exist

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-webui7#75]
During setup version 1.0.41-1 produces following output:
```
File /etc/linuxmuster/webui/config.yml does not exist.
cp: cannot create regular file '/etc/linuxmuster/webui/config.yml': No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
sed: can't read /etc/linuxmuster/webui/config.yml: No such file or directory
Bundle certificate for webui
Run Sophomorix-UI to add permissions
* WebUI Setup Success!
```

**Comment by kiarn** [comment]
Hello @HappyBasher !

What you are mentionning is weird : the file `/etc/linuxmuster/webui/config.yml` is in a test branch `config-linuxmuster` in which we are trying to split the config files.
This error is thrown through the file `/usr/lib/linuxmuster-webui/etc/create_aj_cfg.sh`, and this version should not be in the alpha-package yet.

**Comment by zefanja** [comment]
I got the same error. Workaround is to create the file by yourself. 

> What you are mentionning is weird : the file /etc/linuxmuster/webui/config.yml is in a test branch config-linuxmuster in which we are trying to split the config files.
This error is thrown through the file /usr/lib/linuxmuster-webui/etc/create_aj_cfg.sh, and this version should not be in the alpha-package yet.

Looks like someone packaged exactly this branch for 1.0.41...

**Comment by PLanB2008** [comment]
I fixed some issues in the testing branch and merged it to alpha branch from which on we build our packages.

The packages worked for me and I was able to login for new installations. I'll look into this tomorrow. I assume theres just a minor problem with the hook script we run on package upgrades.

**Comment by kiarn** [comment]
The issue is following : postinst script does the job for a new install, but not split the actual config file for an existing installation. In any case of update without `/etc/linuxmuster/webui/config.yml`, this error will be thrown.

The question is : there is yet not so many existing installations of linuxmuster-webui7, and this error occurs because a major change in the config file behaviour, do we have to implement this in the postinst script ?

It would be easier to let the concerned person solve it with following hint : in an existing installation, the file `/etc/ajenti/config.yml` looks like : 

```
auth:
  allow_sudo: true
  emails: {}
  auth: lm
  users: null
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
linuxmuster:
  initialized: false
  is-configured: false
  ldap:
    binddn: CN=global-binduser,OU=Management,OU=GLOBAL,DC=linuxmuster,DC=lan
    bindpw: blablablablablabla
    host: server
    searchdn: DC=linuxmuster,DC=lan
  provision: false
color: default
language: de
max_sessions: 9
name: server.linuxmuster.lan
restricted_user: nobody
ssl:
  certificate: /ajenti.txt
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: true
```

It has to be split into : 

```
cat /etc/ajenti/config.yml
auth:
  allow_sudo: true
  emails: {}
  auth: lm
  users: null
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: default
language: de
max_sessions: 9
name: server.linuxmuster.lan
restricted_user: nobody
ssl:
  certificate: /ajenti.txt
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: true
```
and 

```
cat /etc/linuxmuster/webui/config.yml 
linuxmuster:
  initialized: false
  is-configured: false
  ldap:
    binddn: CN=global-binduser,OU=Management,OU=GLOBAL,DC=linuxmuster,DC=lan
    bindpw: blablablablablabla
    host: server
    searchdn: DC=linuxmuster,DC=lan
  provision: false
```
Or simply cut the linuxmuster part from the yaml in `/etc/linuxmuster/webui/config.yml`
